spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOSTS}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PWD}
  flyway:
    locations: classpath:db/migration
    schemas: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source: metadata
server:
  port: ${SERVER_PORT}
  servlet:
    contextPath: /schedule/
app:
  team:
    color:
      default: "#000000"
  jwt:
    token:
      prefix: "Bearer "
      headerName: "Authorization"